# NuGet-DontNet-Tool application

trigger: none

variables:
  binDir: bin\Release\net8.0

name: 0.0.$(Date:yy)$(DayOfYear)$(Rev:.r)

resources:
  repositories:
  - repository: templates
    type: git
    name: DFDevOps\cicd-templates
    ref: refs/tags/stable-2
    # https://dev.azure.com/Ceridian/DFDevOps/_git/cicd-templates

jobs:
- job: Build
  pool:
    demands: DotNetFramework
  workspace:
    clean: all
  variables:
  - template: ci/variables.yml@templates

  steps:
  - checkout: self
    clean: true
    lfs: false
    displayName: Checkout ${{ variables['Build.Repository.Name'] }}

  - task: UseDotNet@2
    displayName: Use .NET Core sdk 6.x
    inputs:
      version: 6.x

  - script: |
      echo {"sdk":{"version":"6.x"}} > $(Build.Repository.Name)\src\Tests\Input\5\global.json
    displayName: Create src\Tests\Input\5\global.json

  - template: ci/build-and-test.yml@templates
    parameters:
      checkout: false
      dotNetCoreVersion: 8.x

  - template: ci/nuget-pack-as-tool.yml@templates
    parameters:
      id: GenerateBindingRedirects
      projectDir: src\GenerateBindingRedirects
      binDir: $(binDir)
      buildDir: src\GenerateBindingRedirects\build

  - template: ci/nuget-pack-as-tool.yml@templates
    parameters:
      id: GenerateNuGetUsageReport
      projectDir: src\GenerateNuGetUsageReport
      binDir: $(binDir)
      buildDir: src\GenerateNuGetUsageReport\build

  - template: ci/nuget-pack.yml@templates
    parameters:
      packagesToPack: GenerateBindingRedirects.sln
